language: node_js
os:
  - windows
#  - linux
#  - osx
node_js:
  - 12
  - 10
  - "10.15.0"
  - 8
#  - 6
git:
  depth:
    1

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
